# Generated by Django 4.2.11 on 2024-03-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_option_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name=''),
        ),
    ]
