# Generated by Django 4.2.11 on 2024-03-15 20:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_option_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='image',
        ),
        migrations.AddField(
            model_name='option',
            name='option_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
