# Generated by Django 4.2.11 on 2024-03-26 19:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_rename_option_image_option_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='image',
            field=cloudinary.models.CloudinaryField(default='static/img/awaiting_image.png', max_length=255, verbose_name='image'),
        ),
    ]
