# Generated by Django 4.2.11 on 2024-07-07 18:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_option_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='alt_tag',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
