# Generated by Django 4.2.11 on 2024-07-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_option_alt_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='alt_tag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
