# Generated by Django 4.2.11 on 2024-07-08 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_alter_option_alt_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='alt_tag',
            new_name='alt',
        ),
    ]
